[package]
name = "injective-mocks"
version = "0.1.0"
authors = ["Albert Chon <albert@injectivelabs.org>"]
edition = "2018"
description = "Mocks to use for testing Injective Contracts"
repository = "https://github.com/InjectiveLabs/cw-injective/tree/master/packages/mocks"
license = "Apache-2.0"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
injective-cosmwasm = { path = "../injective-cosmwasm", version = "0.1.0" }
cosmwasm-std = { version = "1.1.1" }
schemars = "0.8.8"
serde = { version = "1.0.136", default-features = false, features = ["derive"] }
