[package]
authors     = [ "Bartek Tofel <tofel.b@gmail.com>" ]
description = "Testing utils for Injective Cosmwasm and core modules"
edition     = "2021"
license     = "Apache-2.0"
name        = "injective-testing"
repository  = "https://github.com/InjectiveLabs/cw-injective/tree/master/packages/injective-testing"
version     = "0.1.4"

[dependencies]
anyhow              = { version = "1.0.66" }
base64              = { version = "0.13.1" }
cosmwasm-std        = { version = "1.2.7", features = [ "abort", "iterator", "stargate" ] }
cw-multi-test       = { version = "0.16.2" }
injective-cosmwasm = { version = "0.2.16", path = "../injective-cosmwasm" }
injective-math     = { version = "0.2.2", path = "../injective-math" }
rand                = { version = "0.4.6" }
secp256k1           = { version = "0.6.2" }
serde               = { version = "1.0.137", default-features = false, features = ["derive"] }
tiny-keccak         = { version = "1.2.1" }
