[package]
description = "Standard library for Injective with CosmWasm support included"
edition     = "2021"
license     = "MIT OR Apache-2.0"
name        = "injective-std"
readme      = "README.md"
repository  = "https://github.com/InjectiveLabs/cw-injective/tree/dev/packages/injective-std"
version     = "1.12.10-testnet-rc2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono             = { version = "0.4.27", default-features = false }
cosmwasm-std       = { version = "1.5.0", features = [ "abort", "cosmwasm_1_2", "cosmwasm_1_3", "cosmwasm_1_4", "iterator", "stargate" ] }
osmosis-std-derive = { version = "0.20.1" }
prost              = { version = "0.12.3", default-features = false, features = [ "prost-derive" ] }
prost-types        = { version = "0.12.3", default-features = false }
schemars           = "0.8.8"
serde              = { version = "1.0", default-features = false, features = [ "derive" ] }
serde-cw-value     = { version = "0.7.0" }
